/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.exportSymbol('proto.io.rsocket.rpc.RSocketMethodOptions', null, global);
goog.exportSymbol('proto.io.rsocket.rpc.options', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.rpc.RSocketMethodOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rsocket.rpc.RSocketMethodOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.rpc.RSocketMethodOptions.displayName = 'proto.io.rsocket.rpc.RSocketMethodOptions';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.rpc.RSocketMethodOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.rpc.RSocketMethodOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.rpc.RSocketMethodOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.rpc.RSocketMethodOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    fireAndForget: jspb.Message.getFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.rpc.RSocketMethodOptions}
 */
proto.io.rsocket.rpc.RSocketMethodOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.rpc.RSocketMethodOptions;
  return proto.io.rsocket.rpc.RSocketMethodOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.rpc.RSocketMethodOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.rpc.RSocketMethodOptions}
 */
proto.io.rsocket.rpc.RSocketMethodOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFireAndForget(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.rpc.RSocketMethodOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.rpc.RSocketMethodOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.rpc.RSocketMethodOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.rpc.RSocketMethodOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFireAndForget();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool fire_and_forget = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.io.rsocket.rpc.RSocketMethodOptions.prototype.getFireAndForget = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.io.rsocket.rpc.RSocketMethodOptions.prototype.setFireAndForget = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `options`.
 * @type {!jspb.ExtensionFieldInfo<!proto.io.rsocket.rpc.RSocketMethodOptions>}
 */
proto.io.rsocket.rpc.options = new jspb.ExtensionFieldInfo(
    1057,
    {options: 0},
    proto.io.rsocket.rpc.RSocketMethodOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.io.rsocket.rpc.RSocketMethodOptions.toObject),
    0);

google_protobuf_descriptor_pb.MethodOptions.extensionsBinary[1057] = new jspb.ExtensionFieldBinaryInfo(
    proto.io.rsocket.rpc.options,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.io.rsocket.rpc.RSocketMethodOptions.serializeBinaryToWriter,
    proto.io.rsocket.rpc.RSocketMethodOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MethodOptions.extensions[1057] = proto.io.rsocket.rpc.options;

goog.object.extend(exports, proto.io.rsocket.rpc);
