/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.io.rsocket.springone.demo.Color', null, global);
goog.exportSymbol('proto.io.rsocket.springone.demo.Data', null, global);
goog.exportSymbol('proto.io.rsocket.springone.demo.Images', null, global);
goog.exportSymbol('proto.io.rsocket.springone.demo.Ranking', null, global);
goog.exportSymbol('proto.io.rsocket.springone.demo.RankingRequest', null, global);
goog.exportSymbol('proto.io.rsocket.springone.demo.Record', null, global);
goog.exportSymbol('proto.io.rsocket.springone.demo.RecordsRequest', null, global);
goog.exportSymbol('proto.io.rsocket.springone.demo.RoundResult', null, global);
goog.exportSymbol('proto.io.rsocket.springone.demo.Urls', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.springone.demo.RecordsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rsocket.springone.demo.RecordsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.springone.demo.RecordsRequest.displayName = 'proto.io.rsocket.springone.demo.RecordsRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.springone.demo.RecordsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.springone.demo.RecordsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.springone.demo.RecordsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.RecordsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    offset: jspb.Message.getFieldWithDefault(msg, 1, 0),
    maxresults: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.springone.demo.RecordsRequest}
 */
proto.io.rsocket.springone.demo.RecordsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.springone.demo.RecordsRequest;
  return proto.io.rsocket.springone.demo.RecordsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.springone.demo.RecordsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.springone.demo.RecordsRequest}
 */
proto.io.rsocket.springone.demo.RecordsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOffset(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxresults(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.springone.demo.RecordsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.springone.demo.RecordsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.springone.demo.RecordsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.RecordsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffset();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMaxresults();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 offset = 1;
 * @return {number}
 */
proto.io.rsocket.springone.demo.RecordsRequest.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.RecordsRequest.prototype.setOffset = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 maxResults = 2;
 * @return {number}
 */
proto.io.rsocket.springone.demo.RecordsRequest.prototype.getMaxresults = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.RecordsRequest.prototype.setMaxresults = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.springone.demo.RoundResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rsocket.springone.demo.RoundResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.springone.demo.RoundResult.displayName = 'proto.io.rsocket.springone.demo.RoundResult';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.springone.demo.RoundResult.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.springone.demo.RoundResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.springone.demo.RoundResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.RoundResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    round: jspb.Message.getFieldWithDefault(msg, 1, 0),
    winner: (f = msg.getWinner()) && proto.io.rsocket.springone.demo.Record.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.springone.demo.RoundResult}
 */
proto.io.rsocket.springone.demo.RoundResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.springone.demo.RoundResult;
  return proto.io.rsocket.springone.demo.RoundResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.springone.demo.RoundResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.springone.demo.RoundResult}
 */
proto.io.rsocket.springone.demo.RoundResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRound(value);
      break;
    case 2:
      var value = new proto.io.rsocket.springone.demo.Record;
      reader.readMessage(value,proto.io.rsocket.springone.demo.Record.deserializeBinaryFromReader);
      msg.setWinner(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.springone.demo.RoundResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.springone.demo.RoundResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.springone.demo.RoundResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.RoundResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRound();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getWinner();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.io.rsocket.springone.demo.Record.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 round = 1;
 * @return {number}
 */
proto.io.rsocket.springone.demo.RoundResult.prototype.getRound = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.RoundResult.prototype.setRound = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Record winner = 2;
 * @return {?proto.io.rsocket.springone.demo.Record}
 */
proto.io.rsocket.springone.demo.RoundResult.prototype.getWinner = function() {
  return /** @type{?proto.io.rsocket.springone.demo.Record} */ (
    jspb.Message.getWrapperField(this, proto.io.rsocket.springone.demo.Record, 2));
};


/** @param {?proto.io.rsocket.springone.demo.Record|undefined} value */
proto.io.rsocket.springone.demo.RoundResult.prototype.setWinner = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.io.rsocket.springone.demo.RoundResult.prototype.clearWinner = function() {
  this.setWinner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.io.rsocket.springone.demo.RoundResult.prototype.hasWinner = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.springone.demo.RankingRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.io.rsocket.springone.demo.RankingRequest.repeatedFields_, null);
};
goog.inherits(proto.io.rsocket.springone.demo.RankingRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.springone.demo.RankingRequest.displayName = 'proto.io.rsocket.springone.demo.RankingRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.io.rsocket.springone.demo.RankingRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.springone.demo.RankingRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.springone.demo.RankingRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.springone.demo.RankingRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.RankingRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    recordsList: jspb.Message.toObjectList(msg.getRecordsList(),
    proto.io.rsocket.springone.demo.Record.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.springone.demo.RankingRequest}
 */
proto.io.rsocket.springone.demo.RankingRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.springone.demo.RankingRequest;
  return proto.io.rsocket.springone.demo.RankingRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.springone.demo.RankingRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.springone.demo.RankingRequest}
 */
proto.io.rsocket.springone.demo.RankingRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.io.rsocket.springone.demo.Record;
      reader.readMessage(value,proto.io.rsocket.springone.demo.Record.deserializeBinaryFromReader);
      msg.addRecords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.springone.demo.RankingRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.springone.demo.RankingRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.springone.demo.RankingRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.RankingRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRecordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.io.rsocket.springone.demo.Record.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Record records = 1;
 * @return {!Array<!proto.io.rsocket.springone.demo.Record>}
 */
proto.io.rsocket.springone.demo.RankingRequest.prototype.getRecordsList = function() {
  return /** @type{!Array<!proto.io.rsocket.springone.demo.Record>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.io.rsocket.springone.demo.Record, 1));
};


/** @param {!Array<!proto.io.rsocket.springone.demo.Record>} value */
proto.io.rsocket.springone.demo.RankingRequest.prototype.setRecordsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.io.rsocket.springone.demo.Record=} opt_value
 * @param {number=} opt_index
 * @return {!proto.io.rsocket.springone.demo.Record}
 */
proto.io.rsocket.springone.demo.RankingRequest.prototype.addRecords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.io.rsocket.springone.demo.Record, opt_index);
};


proto.io.rsocket.springone.demo.RankingRequest.prototype.clearRecordsList = function() {
  this.setRecordsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.springone.demo.Record = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rsocket.springone.demo.Record, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.springone.demo.Record.displayName = 'proto.io.rsocket.springone.demo.Record';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.springone.demo.Record.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.springone.demo.Record.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.springone.demo.Record} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Record.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    data: (f = msg.getData()) && proto.io.rsocket.springone.demo.Data.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.springone.demo.Record}
 */
proto.io.rsocket.springone.demo.Record.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.springone.demo.Record;
  return proto.io.rsocket.springone.demo.Record.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.springone.demo.Record} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.springone.demo.Record}
 */
proto.io.rsocket.springone.demo.Record.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.io.rsocket.springone.demo.Data;
      reader.readMessage(value,proto.io.rsocket.springone.demo.Data.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.springone.demo.Record.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.springone.demo.Record.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.springone.demo.Record} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Record.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.io.rsocket.springone.demo.Data.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.io.rsocket.springone.demo.Record.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.Record.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Data data = 2;
 * @return {?proto.io.rsocket.springone.demo.Data}
 */
proto.io.rsocket.springone.demo.Record.prototype.getData = function() {
  return /** @type{?proto.io.rsocket.springone.demo.Data} */ (
    jspb.Message.getWrapperField(this, proto.io.rsocket.springone.demo.Data, 2));
};


/** @param {?proto.io.rsocket.springone.demo.Data|undefined} value */
proto.io.rsocket.springone.demo.Record.prototype.setData = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.io.rsocket.springone.demo.Record.prototype.clearData = function() {
  this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.io.rsocket.springone.demo.Record.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.springone.demo.Data = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.io.rsocket.springone.demo.Data.repeatedFields_, null);
};
goog.inherits(proto.io.rsocket.springone.demo.Data, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.springone.demo.Data.displayName = 'proto.io.rsocket.springone.demo.Data';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.io.rsocket.springone.demo.Data.repeatedFields_ = [1,2,7,8,10,11,13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.springone.demo.Data.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.springone.demo.Data.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.springone.demo.Data} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Data.toObject = function(includeInstance, msg) {
  var f, obj = {
    aliasesList: jspb.Message.getRepeatedField(msg, 1),
    authorsList: jspb.Message.getRepeatedField(msg, 2),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    images: (f = msg.getImages()) && proto.io.rsocket.springone.demo.Images.toObject(includeInstance, f),
    maincolor: (f = msg.getMaincolor()) && proto.io.rsocket.springone.demo.Color.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 6, ""),
    partnersList: jspb.Message.getRepeatedField(msg, 7),
    powersList: jspb.Message.getRepeatedField(msg, 8),
    ranking: (f = msg.getRanking()) && proto.io.rsocket.springone.demo.Ranking.toObject(includeInstance, f),
    secretidentitiesList: jspb.Message.getRepeatedField(msg, 10),
    speciesList: jspb.Message.getRepeatedField(msg, 11),
    supername: jspb.Message.getFieldWithDefault(msg, 12, ""),
    teamsList: jspb.Message.getRepeatedField(msg, 13),
    urls: (f = msg.getUrls()) && proto.io.rsocket.springone.demo.Urls.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.springone.demo.Data}
 */
proto.io.rsocket.springone.demo.Data.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.springone.demo.Data;
  return proto.io.rsocket.springone.demo.Data.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.springone.demo.Data} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.springone.demo.Data}
 */
proto.io.rsocket.springone.demo.Data.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAliases(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addAuthors(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = new proto.io.rsocket.springone.demo.Images;
      reader.readMessage(value,proto.io.rsocket.springone.demo.Images.deserializeBinaryFromReader);
      msg.setImages(value);
      break;
    case 5:
      var value = new proto.io.rsocket.springone.demo.Color;
      reader.readMessage(value,proto.io.rsocket.springone.demo.Color.deserializeBinaryFromReader);
      msg.setMaincolor(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addPartners(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addPowers(value);
      break;
    case 9:
      var value = new proto.io.rsocket.springone.demo.Ranking;
      reader.readMessage(value,proto.io.rsocket.springone.demo.Ranking.deserializeBinaryFromReader);
      msg.setRanking(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addSecretidentities(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addSpecies(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setSupername(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addTeams(value);
      break;
    case 14:
      var value = new proto.io.rsocket.springone.demo.Urls;
      reader.readMessage(value,proto.io.rsocket.springone.demo.Urls.deserializeBinaryFromReader);
      msg.setUrls(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.springone.demo.Data.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.springone.demo.Data.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.springone.demo.Data} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Data.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAliasesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getAuthorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getImages();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.io.rsocket.springone.demo.Images.serializeBinaryToWriter
    );
  }
  f = message.getMaincolor();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.io.rsocket.springone.demo.Color.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPartnersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getPowersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
  f = message.getRanking();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.io.rsocket.springone.demo.Ranking.serializeBinaryToWriter
    );
  }
  f = message.getSecretidentitiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getSpeciesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getSupername();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getTeamsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getUrls();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.io.rsocket.springone.demo.Urls.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string aliases = 1;
 * @return {!Array<string>}
 */
proto.io.rsocket.springone.demo.Data.prototype.getAliasesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.io.rsocket.springone.demo.Data.prototype.setAliasesList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.io.rsocket.springone.demo.Data.prototype.addAliases = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.io.rsocket.springone.demo.Data.prototype.clearAliasesList = function() {
  this.setAliasesList([]);
};


/**
 * repeated string authors = 2;
 * @return {!Array<string>}
 */
proto.io.rsocket.springone.demo.Data.prototype.getAuthorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.io.rsocket.springone.demo.Data.prototype.setAuthorsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.io.rsocket.springone.demo.Data.prototype.addAuthors = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.io.rsocket.springone.demo.Data.prototype.clearAuthorsList = function() {
  this.setAuthorsList([]);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.io.rsocket.springone.demo.Data.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.io.rsocket.springone.demo.Data.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Images images = 4;
 * @return {?proto.io.rsocket.springone.demo.Images}
 */
proto.io.rsocket.springone.demo.Data.prototype.getImages = function() {
  return /** @type{?proto.io.rsocket.springone.demo.Images} */ (
    jspb.Message.getWrapperField(this, proto.io.rsocket.springone.demo.Images, 4));
};


/** @param {?proto.io.rsocket.springone.demo.Images|undefined} value */
proto.io.rsocket.springone.demo.Data.prototype.setImages = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.io.rsocket.springone.demo.Data.prototype.clearImages = function() {
  this.setImages(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.io.rsocket.springone.demo.Data.prototype.hasImages = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Color mainColor = 5;
 * @return {?proto.io.rsocket.springone.demo.Color}
 */
proto.io.rsocket.springone.demo.Data.prototype.getMaincolor = function() {
  return /** @type{?proto.io.rsocket.springone.demo.Color} */ (
    jspb.Message.getWrapperField(this, proto.io.rsocket.springone.demo.Color, 5));
};


/** @param {?proto.io.rsocket.springone.demo.Color|undefined} value */
proto.io.rsocket.springone.demo.Data.prototype.setMaincolor = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.io.rsocket.springone.demo.Data.prototype.clearMaincolor = function() {
  this.setMaincolor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.io.rsocket.springone.demo.Data.prototype.hasMaincolor = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string name = 6;
 * @return {string}
 */
proto.io.rsocket.springone.demo.Data.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.io.rsocket.springone.demo.Data.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated string partners = 7;
 * @return {!Array<string>}
 */
proto.io.rsocket.springone.demo.Data.prototype.getPartnersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<string>} value */
proto.io.rsocket.springone.demo.Data.prototype.setPartnersList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.io.rsocket.springone.demo.Data.prototype.addPartners = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


proto.io.rsocket.springone.demo.Data.prototype.clearPartnersList = function() {
  this.setPartnersList([]);
};


/**
 * repeated string powers = 8;
 * @return {!Array<string>}
 */
proto.io.rsocket.springone.demo.Data.prototype.getPowersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array<string>} value */
proto.io.rsocket.springone.demo.Data.prototype.setPowersList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.io.rsocket.springone.demo.Data.prototype.addPowers = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


proto.io.rsocket.springone.demo.Data.prototype.clearPowersList = function() {
  this.setPowersList([]);
};


/**
 * optional Ranking ranking = 9;
 * @return {?proto.io.rsocket.springone.demo.Ranking}
 */
proto.io.rsocket.springone.demo.Data.prototype.getRanking = function() {
  return /** @type{?proto.io.rsocket.springone.demo.Ranking} */ (
    jspb.Message.getWrapperField(this, proto.io.rsocket.springone.demo.Ranking, 9));
};


/** @param {?proto.io.rsocket.springone.demo.Ranking|undefined} value */
proto.io.rsocket.springone.demo.Data.prototype.setRanking = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.io.rsocket.springone.demo.Data.prototype.clearRanking = function() {
  this.setRanking(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.io.rsocket.springone.demo.Data.prototype.hasRanking = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated string secretIdentities = 10;
 * @return {!Array<string>}
 */
proto.io.rsocket.springone.demo.Data.prototype.getSecretidentitiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/** @param {!Array<string>} value */
proto.io.rsocket.springone.demo.Data.prototype.setSecretidentitiesList = function(value) {
  jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.io.rsocket.springone.demo.Data.prototype.addSecretidentities = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


proto.io.rsocket.springone.demo.Data.prototype.clearSecretidentitiesList = function() {
  this.setSecretidentitiesList([]);
};


/**
 * repeated string species = 11;
 * @return {!Array<string>}
 */
proto.io.rsocket.springone.demo.Data.prototype.getSpeciesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<string>} value */
proto.io.rsocket.springone.demo.Data.prototype.setSpeciesList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.io.rsocket.springone.demo.Data.prototype.addSpecies = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


proto.io.rsocket.springone.demo.Data.prototype.clearSpeciesList = function() {
  this.setSpeciesList([]);
};


/**
 * optional string superName = 12;
 * @return {string}
 */
proto.io.rsocket.springone.demo.Data.prototype.getSupername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.io.rsocket.springone.demo.Data.prototype.setSupername = function(value) {
  jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * repeated string teams = 13;
 * @return {!Array<string>}
 */
proto.io.rsocket.springone.demo.Data.prototype.getTeamsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/** @param {!Array<string>} value */
proto.io.rsocket.springone.demo.Data.prototype.setTeamsList = function(value) {
  jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.io.rsocket.springone.demo.Data.prototype.addTeams = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


proto.io.rsocket.springone.demo.Data.prototype.clearTeamsList = function() {
  this.setTeamsList([]);
};


/**
 * optional Urls urls = 14;
 * @return {?proto.io.rsocket.springone.demo.Urls}
 */
proto.io.rsocket.springone.demo.Data.prototype.getUrls = function() {
  return /** @type{?proto.io.rsocket.springone.demo.Urls} */ (
    jspb.Message.getWrapperField(this, proto.io.rsocket.springone.demo.Urls, 14));
};


/** @param {?proto.io.rsocket.springone.demo.Urls|undefined} value */
proto.io.rsocket.springone.demo.Data.prototype.setUrls = function(value) {
  jspb.Message.setWrapperField(this, 14, value);
};


proto.io.rsocket.springone.demo.Data.prototype.clearUrls = function() {
  this.setUrls(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.io.rsocket.springone.demo.Data.prototype.hasUrls = function() {
  return jspb.Message.getField(this, 14) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.springone.demo.Images = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rsocket.springone.demo.Images, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.springone.demo.Images.displayName = 'proto.io.rsocket.springone.demo.Images';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.springone.demo.Images.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.springone.demo.Images.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.springone.demo.Images} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Images.toObject = function(includeInstance, msg) {
  var f, obj = {
    background: jspb.Message.getFieldWithDefault(msg, 1, ""),
    thumbnail: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.springone.demo.Images}
 */
proto.io.rsocket.springone.demo.Images.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.springone.demo.Images;
  return proto.io.rsocket.springone.demo.Images.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.springone.demo.Images} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.springone.demo.Images}
 */
proto.io.rsocket.springone.demo.Images.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBackground(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setThumbnail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.springone.demo.Images.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.springone.demo.Images.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.springone.demo.Images} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Images.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBackground();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getThumbnail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string background = 1;
 * @return {string}
 */
proto.io.rsocket.springone.demo.Images.prototype.getBackground = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.io.rsocket.springone.demo.Images.prototype.setBackground = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string thumbnail = 2;
 * @return {string}
 */
proto.io.rsocket.springone.demo.Images.prototype.getThumbnail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.io.rsocket.springone.demo.Images.prototype.setThumbnail = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.springone.demo.Color = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rsocket.springone.demo.Color, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.springone.demo.Color.displayName = 'proto.io.rsocket.springone.demo.Color';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.springone.demo.Color.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.springone.demo.Color.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.springone.demo.Color} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Color.toObject = function(includeInstance, msg) {
  var f, obj = {
    red: jspb.Message.getFieldWithDefault(msg, 1, 0),
    green: jspb.Message.getFieldWithDefault(msg, 2, 0),
    blue: jspb.Message.getFieldWithDefault(msg, 3, 0),
    hexa: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.springone.demo.Color}
 */
proto.io.rsocket.springone.demo.Color.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.springone.demo.Color;
  return proto.io.rsocket.springone.demo.Color.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.springone.demo.Color} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.springone.demo.Color}
 */
proto.io.rsocket.springone.demo.Color.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRed(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGreen(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBlue(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setHexa(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.springone.demo.Color.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.springone.demo.Color.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.springone.demo.Color} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Color.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRed();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getGreen();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getBlue();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getHexa();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional int32 red = 1;
 * @return {number}
 */
proto.io.rsocket.springone.demo.Color.prototype.getRed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.Color.prototype.setRed = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 green = 2;
 * @return {number}
 */
proto.io.rsocket.springone.demo.Color.prototype.getGreen = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.Color.prototype.setGreen = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 blue = 3;
 * @return {number}
 */
proto.io.rsocket.springone.demo.Color.prototype.getBlue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.Color.prototype.setBlue = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string hexa = 4;
 * @return {string}
 */
proto.io.rsocket.springone.demo.Color.prototype.getHexa = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.io.rsocket.springone.demo.Color.prototype.setHexa = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.springone.demo.Ranking = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rsocket.springone.demo.Ranking, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.springone.demo.Ranking.displayName = 'proto.io.rsocket.springone.demo.Ranking';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.springone.demo.Ranking.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.springone.demo.Ranking.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.springone.demo.Ranking} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Ranking.toObject = function(includeInstance, msg) {
  var f, obj = {
    comiccount: jspb.Message.getFieldWithDefault(msg, 1, 0),
    eventcount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageviewcount: jspb.Message.getFieldWithDefault(msg, 3, 0),
    seriecount: jspb.Message.getFieldWithDefault(msg, 4, 0),
    storycount: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.springone.demo.Ranking}
 */
proto.io.rsocket.springone.demo.Ranking.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.springone.demo.Ranking;
  return proto.io.rsocket.springone.demo.Ranking.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.springone.demo.Ranking} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.springone.demo.Ranking}
 */
proto.io.rsocket.springone.demo.Ranking.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setComiccount(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEventcount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageviewcount(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSeriecount(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStorycount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.springone.demo.Ranking.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.springone.demo.Ranking.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.springone.demo.Ranking} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Ranking.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getComiccount();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getEventcount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPageviewcount();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSeriecount();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getStorycount();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional int32 comicCount = 1;
 * @return {number}
 */
proto.io.rsocket.springone.demo.Ranking.prototype.getComiccount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.Ranking.prototype.setComiccount = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 eventCount = 2;
 * @return {number}
 */
proto.io.rsocket.springone.demo.Ranking.prototype.getEventcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.Ranking.prototype.setEventcount = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 pageviewCount = 3;
 * @return {number}
 */
proto.io.rsocket.springone.demo.Ranking.prototype.getPageviewcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.Ranking.prototype.setPageviewcount = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 serieCount = 4;
 * @return {number}
 */
proto.io.rsocket.springone.demo.Ranking.prototype.getSeriecount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.Ranking.prototype.setSeriecount = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 storyCount = 5;
 * @return {number}
 */
proto.io.rsocket.springone.demo.Ranking.prototype.getStorycount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.io.rsocket.springone.demo.Ranking.prototype.setStorycount = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.rsocket.springone.demo.Urls = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.rsocket.springone.demo.Urls, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.rsocket.springone.demo.Urls.displayName = 'proto.io.rsocket.springone.demo.Urls';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.rsocket.springone.demo.Urls.prototype.toObject = function(opt_includeInstance) {
  return proto.io.rsocket.springone.demo.Urls.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.rsocket.springone.demo.Urls} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Urls.toObject = function(includeInstance, msg) {
  var f, obj = {
    marvel: jspb.Message.getFieldWithDefault(msg, 1, ""),
    wikipedia: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.rsocket.springone.demo.Urls}
 */
proto.io.rsocket.springone.demo.Urls.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.rsocket.springone.demo.Urls;
  return proto.io.rsocket.springone.demo.Urls.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.rsocket.springone.demo.Urls} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.rsocket.springone.demo.Urls}
 */
proto.io.rsocket.springone.demo.Urls.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMarvel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWikipedia(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.rsocket.springone.demo.Urls.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.rsocket.springone.demo.Urls.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.rsocket.springone.demo.Urls} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.rsocket.springone.demo.Urls.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarvel();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWikipedia();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string marvel = 1;
 * @return {string}
 */
proto.io.rsocket.springone.demo.Urls.prototype.getMarvel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.io.rsocket.springone.demo.Urls.prototype.setMarvel = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string wikipedia = 2;
 * @return {string}
 */
proto.io.rsocket.springone.demo.Urls.prototype.getWikipedia = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.io.rsocket.springone.demo.Urls.prototype.setWikipedia = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.io.rsocket.springone.demo);
