= Setup

In our application we have two central components that requires to be setup.


== Setup Postgres

The first component is Postgres. In order to run the demo Postgres database, we are using Docker. The following command creates the initial docker container with Postgres database:

[source,sh]
docker run \
  --name postgres \
  -p 5432:5432 \
  -e POSTGRES_DB="marvel" \
  -e POSTGRES_USER="captain" \
  -e POSTGRES_PASSWORD="america" \
  postgres

Once the container is created and run we need to execute a list of commands that prepare the required data. Make sure that the commands it executed within the project root folder:

[source,sh]
docker cp ./records.json postgres:records.json

By running the above command we will copy the records with Superhero stats and descriptions of the created container.
Once the data is upload we need to execute a few remote SQL commands that create `records` table and prepare index:

[source,sh]
docker exec -ti postgres sh -c 'psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE TABLE records ( id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, data jsonb NOT NULL )"'

[source,sh]
docker exec -ti postgres sh -c 'psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE INDEX records_data_gin_idx ON records USING GIN(data)"'

Once the `records` table is created we may upload data from the `records.json` file:

[source, sh]
docker exec -ti postgres sh -c 'cat records.json | psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "COPY records (data) FROM STDIN;"'

== Setup Proteus Broker

Along with Postgres, we have an additional component required for running Proteus Framework called Proteus Broker. Proteus Broker is a zero-copy data-routing service which is responsible for connecting microservices. In order to run the Proteus Broker
we need to create and run dockerized instance of Proteus Broker using the following command:

[source,sh]
docker run \
  -p 8001:8001 \
  -p 8101:8101 \
  -p 7001:7001 \
  -e BROKER_SERVER_OPTS="'-Dnetifi.authentication.0.accessKey=9007199254740991'  \
  '-Dnetifi.authentication.0.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY=' \
  '-Dnetifi.broker.admin.accessKey=9007199254740991' \
  '-Dnetifi.broker.admin.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY=' \
  '-Dnetifi.broker.ssl.disabled=true'" \
  netifi/proteus


By running the above commands, we make available for the usage the Proteus Borker, which is the last prerequisite for our Reactive System. In the next section, we are going to learn the design of our System and get some understanding of the interaction model between services.
